version: '3.3'
services:
  oraclixmysqldev:
    container_name: oraclixMysqlDev
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
    volumes:
      - ./docker/mysql_init:/docker-entrypoint-initdb.d
      - ./data:/var/lib/mysql
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
  oraclixbackenddev:
    container_name: oraclixDbDev
    restart: always
    build: .
    volumes:
      - ./src:/usr/src/app
      #- /usr/src/app/node_modules
    command: npm run development
    ports:
      - "3008:3008"
