USE `zorahDb`;
DROP TABLE IF EXISTS answer;
DROP TABLE IF EXISTS discord_guild;
DROP TABLE IF EXISTS discord_user;
DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS question;
DROP TABLE IF EXISTS report;
